version: '3.8'

services:
  app:
    image: library-app
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: library-app

  server:
    image: library-server
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 4000:4000
    container_name: library-server
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
